language: node_js
node_js: node
script: npm run build
deploy:
  provider: pages
  local-dir: _book
  name: Denys Dovhan
  email: email@denysdovhan.com
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  on:
    branch: master
env:
  global:
    secure: lfGtlu6hEusjeTxcjm+oBTN8Qudyb2fR91YqxnaKHhw3PZs/gA80g0voEwdn1t1CO0WXqGAAYiEn6iQPE38swSLrbxv2CskYapaxIV5gB5Ec64EcESemFAf2eONGA2SlzDQI6YSxmR61yTW4uSAH7UQ1y6hovqyGAYgyNAAlyzFdn1IUn5cD6WG9XBFWbU6Tt2QxysXrpjghkydcgZdEJqMXZwpK4B3cYJDWBpJodG+IVaWdi/aJihj2TAHfV036lrhaR+sZgVsm2nI3YG9gpNpqPFwboQWSz5mxTu2cgVVV2mMo2KtmUOVAxfmkl6XsAo8gk4M/qBWeVMgv63CbbkgtU8TIqEBCPdZRjJWmzzp+FBI5WRbqzw3+BXo0NIFnIWax4ldUgQSfl2oO8Wkmv7Snj5LDiZFC4cPCZlHIQx2eujjgxi8zzSIFm+l812t6bjxNZbRJiKJYs5dM2ROybGaRoAsULKeTK5H9QmCbySbWlkh6Py47AqV+l9uO+HupMz3LKhi2L4sQLTpT12WJDhAbLi2ne85CR1Xsxc1Usy03dvDXoIVjCthow9P/VFp17ylmvbfZdO94Xfb5ZC15kb7xX/2HUq6D+Ya0k28h2l6ZDOiiyTJK8WbrJspY5Euq1qSxs0TF9HQUy05MsFgC47kNr9smQy8EGccKs68E4fQ=
notifications:
  slack:
    secure: GRnQ0+Jx1OsHG4mAxgoXQ5dpK1PZnm8OA8k4/hrK+HeewQZHGRTETALy51pnmGzIR6BufXbBuV+L45JsX5y7HKgvcpAV4ENkkKvehmEsOC8ER0oHHNUym5x8p0/NbypH+2BraIKKSknGtH2/Vpzb0lh1cRx58Oplh+DsvD6bTsXKARQFe2Y4ejnKjAoSQ51qK2YNcwe4oCTCNhV3ahwTrX6nwHEwBkJ3Ybi3wdnBDOSUOgtwC9TRKgt9A5JDkrPQem57MfBk/i0DqKAw1JUyTm6JHDEM1GoCQFdDsPtKKSq81BE7lsZYjfdC61a/Z0BsGF/KSgPKS9d49FIz7LkfTGIvRgECYAdNlz4AA2pCfBGOomKTAAApPHqlc2Ve4xAVgvFiStM9u8YhBKxfe/oL6FmpeB+DOeExCHu3u7sZDrFUw/Z9reSmyd1HxSTpwTOBrpRYHesaQysyucRJjT7DSy97Q6TPoEptr7Z4priMPF4a7uo1votx10vmzjBomdQCijQMBN4mtTQIiRiZPvlNUEILLqToXmw1Ta8DFzbI7IEZ8UcY6HGYBhrlTp2w7flqhqIsejm9rvcF8gKDMgfdkEXxcqqv0PG+SaSLb4hU+DKJdAapAymcNEQWZv0qwJyY3FhUY4i4JwDo+FF9ioGBiwHR1cOyt2TgrPp4mrJXa9Q=
