language: node_js
node_js: node
script: npm run build
deploy:
  provider: pages
  local-dir: _book
  name: Denys Dovhan
  email: email@denysdovhan.com
  keep-history: true
  allow-empty-commit: true
  # fqdn: {{custom_domain_here}}
  skip-cleanup: true
  on:
    branch: master
  github-token:
    secure:
      g8QI37gaPzl5CsE6UoImabDAg4BQNWNMHHzVm2wQu+yUDPSY19RYSEbDYOmW+Iwotb8gxMa36uFbhB9QW3D1tdUT6b4Nx3cDRwgg8wx05qmmiz117OecAKOGtsz/4YSGExFKiyVO5mWB/VZe00WUOm1DR8ZciIIGOflNDGF07m+Gfto0KeGWNei6XyrtFKEI12Imi9WbtTJkmjTh4XXITuzcM+/YONJzscLKE6k/VcgTgLx/GeFXl1LiGH15VUJJuiE0/90Kbtz2bdKk4aWAPjiFeaA60VKrKLIq8+bGc1Pk6if91itMS6kXKXi3VM8llc5BiYXRdB6zJBXanjChr8LmW8XHGNP5o3NOY26qmjowvzxwMSsmv6lpu1GBD0b+43H9QdH+amZby+YaVQob0HUtNOzLNdnU2JzhimsLS3Bpfp6b6FDcZqWLC7x7JSeFSJLnh0erUdRCh/xREUjhQDvn73g6tRGqdp5ahxoB+uXsF40hYm3MkwSjwfGr+ezMXQ5iJSlA7f1VJOcjwJuCwsisoIGezY9ScXGJFVADTnvzhY1wLrHbMRLTFTdQme4ZMi+ZfLztrNS5lOH1FYvngTvZYWigst3Bzg1BmuoOPghpt8c9prW4IEIdLRKXrZMei+0z2KmEhck7Noade4Cx46qai09EcDXO3dJPI5QhyA0=
notifications:
  slack:
    secure: GRnQ0+Jx1OsHG4mAxgoXQ5dpK1PZnm8OA8k4/hrK+HeewQZHGRTETALy51pnmGzIR6BufXbBuV+L45JsX5y7HKgvcpAV4ENkkKvehmEsOC8ER0oHHNUym5x8p0/NbypH+2BraIKKSknGtH2/Vpzb0lh1cRx58Oplh+DsvD6bTsXKARQFe2Y4ejnKjAoSQ51qK2YNcwe4oCTCNhV3ahwTrX6nwHEwBkJ3Ybi3wdnBDOSUOgtwC9TRKgt9A5JDkrPQem57MfBk/i0DqKAw1JUyTm6JHDEM1GoCQFdDsPtKKSq81BE7lsZYjfdC61a/Z0BsGF/KSgPKS9d49FIz7LkfTGIvRgECYAdNlz4AA2pCfBGOomKTAAApPHqlc2Ve4xAVgvFiStM9u8YhBKxfe/oL6FmpeB+DOeExCHu3u7sZDrFUw/Z9reSmyd1HxSTpwTOBrpRYHesaQysyucRJjT7DSy97Q6TPoEptr7Z4priMPF4a7uo1votx10vmzjBomdQCijQMBN4mtTQIiRiZPvlNUEILLqToXmw1Ta8DFzbI7IEZ8UcY6HGYBhrlTp2w7flqhqIsejm9rvcF8gKDMgfdkEXxcqqv0PG+SaSLb4hU+DKJdAapAymcNEQWZv0qwJyY3FhUY4i4JwDo+FF9ioGBiwHR1cOyt2TgrPp4mrJXa9Q=
